version: '3'

services:
  Shriek.CMS.services:
    image: Shriek.CMS.services
    build:
      context: .
      dockerfile: src/Shriek.CMS.Services/Dockerfile

  Shriek.CMS.admin:
    image: Shriek.CMS.admin
    build:
      context: .
      dockerfile: src/Shriek.CMS.Admin/Dockerfile


  Shriek.CMS.web:
    image: Shriek.CMS.web
    build:
      context: .
      dockerfile: src/Shriek.CMS.Web/Dockerfile

