version: '3'

services:
  shriekfx.cms.services:
    environment:
      - ASPNETCORE_ENVIRONMENT=Development
    ports:
      - "80"

  shriekfx.cms.admin:
    environment:
      - ASPNETCORE_ENVIRONMENT=Development
    ports:
      - "80"


  shriekfx.cms.web:
    environment:
      - ASPNETCORE_ENVIRONMENT=Development
    ports:
      - "80"

